create table user_account
(
    user_id            bigint generated by default as identity,
    first_name    varchar(55),
    last_name     varchar(55),
    user_level    varchar(55),
    email_address varchar(255),
    phone_number  varchar(255),
    address       varchar(255),

    primary key (user_id)
);
create table items
(
    item_id              bigint generated by default as identity,
    name            varchar(255),
    description     varchar(255),
    price           float8,
    amount_in_stock int8,
    primary key (item_id)
);

create table orders
(
    order_number bigint generated by default as identity,
    fk_customer_id bigint,
    price float8,
    items varchar(510),
    primary key(order_number),
    foreign key (fk_customer_id) references user_account
);